services:
  mongodb:
    image: mongo:latest
    container_name: peekle-mongodb
    ports:
      - "21005:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
